name: VansJoin
main: me.ivanech.vansjoin.VansJoin
version: 1.0.0-beta
api-version: 1.16
softdepend:
  - PlaceholderAPI
commands:
  vj:
    description: VansJoin base command
    aliases: [vansjoin]
    usage: /<command> [help|reload]
    permission: vansjoin.command
permissions:
  vansjoin.command:
    description: Access to VansJoin commands
    default: true
  vansjoin.reload:
    description: Reload VansJoin configuration
    default: op
  vansjoin.alert:
    description: Receive VansJoin join alert
    default: false
name: VansJoin
main: me.ivanech.vansjoin.VansJoin
version: 1.0.0
api-version: 1.16
softdepend:
  - PlaceholderAPI
commands:
  vj:
    description: VansJoin info
    aliases: [vansjoin]
    usage: /<command>

